### ISSUE TITLE
Non-binary excluding language on site

### ISSUE THREAD

**Issue by pnasrat** [CUNYCWIC/CUNYWiC2019#1]
I definitely understand there is nuance in thinking about gendered spaces, however there are a number of non-binary folks working in tech and the event appears to exclude, a suggestion for language might be  `engagement and participation of all genders`. 

>  The CUNYCWiC aims to encourage the engagement and the participation of women and men in a wide range of computer science related research and projects and to provide networking opportunities and explorations of careers in computing

**Comment by CUNYCWIC** [comment]
The language has been updated on the homepage!
